### ISSUE TITLE
Clicking "Privacy" link-button, on the top-right, triggers an error

### ISSUE THREAD

**Issue by felladrin** [flatsiedatsie/papeg_ai#1]
Clicking:
<img width="116" alt="image" src="https://github.com/user-attachments/assets/c171bd61-870b-442f-87a8-705dda97b592">

Triggers:
<img width="305" alt="image" src="https://github.com/user-attachments/assets/e03a82f1-9b0e-447e-bbf4-5abd5d76e6a1">

And nothing else happens visually.

Browser: Brave

---

But I just tested it in Safari browser, and it worked fine.

So it seems it's Brave Browser blocking it.

**Comment by flatsiedatsie** [comment]
Thank you. How ironic, blocking the privacy policy.. I've pre-loaded the files for now. Perhaps it's a CORS issue.. which is not my forte.
