### ISSUE TITLE
Thanks for great app. Can it be somehow compiled to .exe file?

### ISSUE THREAD

**Issue by JohnClaw** [flatsiedatsie/papeg_ai#2]
...

**Comment by flatsiedatsie** [comment]
It's a website :-D

I guess maybe using [Electron](https://www.electronjs.org/)? But I have no experience with that.

The site is already designed to work as a web-app. Once an AI is downloaded you can disconnect the WiFi and it will continue working. You can even refresh the page, and it will magically appear again, as if you're still connected to the internet.
