### ISSUE TITLE
Advanced Image Creator generation bug

### ISSUE THREAD

**Issue by Farsinuce** [flatsiedatsie/papeg_ai#3]
When generating an image using "Advanced Image Creator", it seemingly bugs out and get stuck, but after a while, the image appears under "Image Creator".

Chrome console log: [papeg.ai-1728637029770.log](https://github.com/user-attachments/files/17340353/papeg.ai-1728637029770.log)

Prompt result (beware): "[a 35 mm marketing shot of a woman at summer, warm sunlight on her face, and she is smiling](https://files.catbox.moe/m5xwr0.png)"

![2024-10-11-000678](https://github.com/user-attachments/assets/874d045f-8c46-4372-ada6-ca264bd99943)

![2024-10-11-000679](https://github.com/user-attachments/assets/d2321363-c32a-4377-acc4-023a6362486e)

**Comment by mounta11n** [comment]
> Prompt result (beware)

..the hell xD

**Comment by flatsiedatsie** [comment]
I found the bug, it will be fixed in the next version (soon).

Thanks you for pointing it out!

**Comment by flatsiedatsie** [comment]
The beta version of Papeg.ai can be found at www.papegai.eu . I'll update it with the fix now.
